EADDreamCarProject/Controllers/BuyCarsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EADDreamCarProject.Models;

namespace EADDreamCarProject.Controllers
{
    public class BuyCarsController : Controller
    {
        private Model1 db = new Model1();

        // GET: BuyCars
        public ActionResult Index()
        {
            var customers = db.Customers.Include(c => c.CarModel).Include(c => c.Company);
            return View(customers.ToList());
        }

        // GET: BuyCars/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // GET: BuyCars/Create
        public ActionResult Create()
        {
            ViewBag.CarModelFID = new SelectList(db.CarModels, "CarModelID", "CarModelName");
            ViewBag.CompanyFID = new SelectList(db.Companies, "CompanyID", "CompanyName");
            return View();
        }

        // POST: BuyCars/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Customer customer)
        {
            if (ModelState.IsValid)
            {
                customer.CustomerPic.SaveAs(Server.MapPath("~/dbPictures/" + customer.CustomerPic.FileName));
                customer.CustomerPicture = "~/dbPictures/" + customer.CustomerPic.FileName;
                db.Customers.Add(customer);
                db.SaveChanges();
                return RedirectToAction("Client","Home");
            }

            ViewBag.CarModelFID = new SelectList(db.CarModels, "CarModelID", "CarModelName", customer.CarModelFID);
            ViewBag.CompanyFID = new SelectList(db.Companies, "CompanyID", "CompanyName", customer.CompanyFID);
            return View(customer);
        }

        // GET: BuyCars/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            ViewBag.CarModelFID = new SelectList(db.CarModels, "CarModelID", "CarModelName", customer.CarModelFID);
            ViewBag.CompanyFID = new SelectList(db.Companies, "CompanyID", "CompanyName", customer.CompanyFID);
            return View(customer);
        }

        // POST: BuyCars/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CustomerID,CustomerName,CustomerCity,CustomerAddress,CustomerContact,CustomerEmail,CompanyFID,CarModelFID,CustomerPicture")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(customer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CarModelFID = new SelectList(db.CarModels, "CarModelID", "CarModelName", customer.CarModelFID);
            ViewBag.CompanyFID = new SelectList(db.Companies, "CompanyID", "CompanyName", customer.CompanyFID);
            return View(customer);
        }

        // GET: BuyCars/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: BuyCars/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Customer customer = db.Customers.Find(id);
            db.Customers.Remove(customer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EADDreamCarProject/Controllers/HomeController.cs
using EADDreamCarProject.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EADDreamCarProject.Controllers
{
    public class HomeController : Controller
    {
        Model1 db = new Model1();
        public ActionResult IndexAdmin()
        {
            return View();
        }
        public ActionResult IndexCustomer()
        {
            DisplayHomePage dhp=new DisplayHomePage();
            dhp.HomeComp = db.Companies.ToList();
            dhp.HomeCarMod = db.CarModels.ToList();
            dhp.HomeAdm=db.Admins.ToList();
            return View(dhp);
        }

        public ActionResult About()
        {
            return View(db.Admins.ToList());
        }

        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(Admin a)
        {
            //please count records from database admin table where table email and password is matched with our posted email and
            //password, if email and password matched result is 1, else result would be 0.
            //Admin a mai jo type kiya data wo ata
            int result = db.Admins.Where(x => x.AdminEmail == a.AdminEmail && x.AdminPassword == a.AdminPassword).Count();
            if (result == 1)
            {
                return RedirectToAction("IndexAdmin", "Home");
            }
            else
            {
                ViewBag.Message = "Invalid Email or Password.";
                return View();
            }

        }

        public ActionResult Cart()
        {
            List<CarModel> CarList = new List<CarModel>();
            Session["MyCart"] = CarList;
            return View();
        }

        public ActionResult AddToCart(int id)
        {
            List<CarModel> CarList = new List<CarModel>();
            CarList.Add(db.CarModels.Where(x => x.CarModelID == id).FirstOrDefault());
            Session["MyCart"]=CarList; //yeh hum ne is liye use kiya tah k jo hum ne new list banai jis
                                       //mai specific cart wali gariya hein unhe kisi b page peh use kar
                                       //sake bas is k liye us specific page peh ja k hame Models ko
                                       //declare karna ho ga
            return RedirectToAction("Cart");
        }

        public ActionResult DisplayCarModel(int? id)
        {
            DisplayCar dc = new DisplayCar();
            dc.Comp = db.Companies.ToList();
            if(id==null)
            {
                dc.CarMod = db.CarModels.ToList();
            }
            else
            {
                dc.CarMod = db.CarModels.Where(x=>x.CompanyFID==id).ToList();
            }
            
            return View(dc);
        }

        public ActionResult DisplayShowroom()
        {
            return View(db.Showrooms.ToList());
        }

        public ActionResult Client(int? id)
        {
            DisplayClient dcl = new DisplayClient();
            dcl.CompanyList = db.Companies.ToList();
            if(id == null)
            {
                dcl.CustomerList = db.Customers.ToList();
            }
            else
            {
                dcl.CustomerList = db.Customers.Where(x=>x.CompanyFID==id).ToList();
            }
            
            return View(dcl);
        }

    }
}

EADDreamCarProject/Views/Home/About.cshtml
@model IEnumerable<EADDreamCarProject.Models.Admin>
@{
    Layout = "~/Views/Shared/_LayoutCustomer.cshtml";
}

<!-- Start All Title Box -->
<div class="all-title-box">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h2>ABOUT US</h2>
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a href="@Url.Action("IndexCustomer","Home")">Home</a></li>
                    <li class="breadcrumb-item active">ABOUT US</li>
                </ul>
            </div>
        </div>
    </div>
</div>
<!-- End All Title Box -->
<!-- Start About Page  -->
<div class="about-box-main">
    <div class="container">
        <div class="row my-1">
            <div class="col-sm-6 col-lg-4">
                <div class="service-block-inner">
                    <h3>We are Trusted</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
                </div>
            </div>
            <div class="col-sm-6 col-lg-4">
                <div class="service-block-inner">
                    <h3>We are Professional</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
                </div>
            </div>
            <div class="col-sm-6 col-lg-4">
                <div class="service-block-inner">
                    <h3>We are Expert</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
                </div>
            </div>
        </div>

 
           
            <div class="row">
                <div class="col-12">
                    <center><h2 class="noo-sh-title">Meet Our Team</h2></center>
                </div>

                @foreach (var item in Model)
                {
                    <div class="col-md-6 col-lg-4 col-xl-4">
                        <div class="blog-box">
                            <div class="blog-img">
                                <img height="300vh" width="100%" src="@Url.Content(item.AdminPicture)" alt="" />
                            </div>
                            <center>
                                <div class="blog-content">
                                    <div class="title-blog" >
                                        <h1 style="color:red; font-weight:bolder;">@item.AdminName</h1>
                                        <p style="color:blue; font-size:1.2em;">@item.AdminEmail</p>

                                    </div>
                                </div>
                            </center>
                        </div>



                    </div>
                }


            </div>

    </div>
</div>
<!-- End About Page -->

EADDreamCarProject/Views/Home/Cart.cshtml
@using EADDreamCarProject.Models <!--yeh hum ne session ko yaha use karne k liye likha-->
@{
    Layout = "~/Views/Shared/_LayoutCustomer.cshtml";
}

<!-- Start All Title Box -->
<div class="all-title-box">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h2>Cart</h2>
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a href="@Url.Action("DisplayCarModel","Home")">Cars</a></li>
                    <li class="breadcrumb-item active">Cart</li>
                </ul>
            </div>
        </div>
    </div>
</div>
<!-- End All Title Box -->
<!-- Start Cart  -->
<div class="cart-box-main">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="table-main table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Picture</th>
                                <th>Model Name</th>
                                <th>Description</th>
                                <th>Price</th>
                                <th>Quantity</th>
                                <th>Total</th>
                                <th>Remove</th>
                            </tr>
                        </thead>
                        <tbody>
                            <!--yeh hum ne is ko
                            bata k bhai hum ek List use karna chahte CarModel (jo k hamara model
                            hai) us ki or Session jo k hamara MyCart k name se hai-->
                            
                            @foreach (var item in (List<CarModel>)Session["MyCart"])
                            {
                                <tr>
                                    <td class="thumbnail-img">
                                        <a href="#">
                                            <img class="img-fluid" src="@Url.Content(item.CarModelPicture)" alt="" />
                                        </a>
                                    </td>
                                    <td class="name-pr">
                                        <a href="#">
                                            @item.CarModelName
                                        </a>
                                    </td>
                                    <td class="name-pr">
                                        <a href="#">
                                            @item.CarModelDescription
                                        </a>
                                    </td>
                                    <td class="price-pr">
                                        <p>Rs. @item.CarModelPrice</p>
                                    </td>
                                    <td class="quantity-box">
                                        <a class="btn btn-danger fa fa-minus" style="color:white"></a>
                                        <b> 1 </b>
                                        <a class="btn btn-danger fa fa-plus" style="color:white"></a>
                                    </td>
                                    <td class="total-pr">
                                        <p></p>
                                    </td>
                                    <td class="remove-pr">
                                        <a href="#">
                                            <i class="fas fa-times"></i>
                                        </a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

        <div class="row my-5">
            <div class="col-lg-6 col-sm-6">
                <div class="coupon-box">
                    <div class="input-group input-group-sm">
                        <input class="form-control" placeholder="Enter your coupon code" aria-label="Coupon code" type="text">
                        <div class="input-group-append">
                            <button class="btn btn-theme" type="button">Apply Coupon</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 col-sm-6">
                <div class="update-box">
                    <input value="Update Cart" type="submit">
                </div>
            </div>
        </div>

        <div class="row my-5">
            <div class="col-lg-8 col-sm-12"></div>
            <div class="col-lg-4 col-sm-12">
                <div class="order-box">
                    <h3>Order summary</h3>
                    <div class="d-flex">
                        <h4>Sub Total</h4>
                        <div class="ml-auto font-weight-bold"> $ 130 </div>
                    </div>
                    <div class="d-flex">
                        <h4>Discount</h4>
                        <div class="ml-auto font-weight-bold"> $ 40 </div>
                    </div>
                    <hr class="my-1">
                    <div class="d-flex">
                        <h4>Coupon Discount</h4>
                        <div class="ml-auto font-weight-bold"> $ 10 </div>
                    </div>
                    <div class="d-flex">
                        <h4>Tax</h4>
                        <div class="ml-auto font-weight-bold"> $ 2 </div>
                    </div>
                    <div class="d-flex">
                        <h4>Shipping Cost</h4>
                        <div class="ml-auto font-weight-bold"> Free </div>
                    </div>
                    <hr>
                    <div class="d-flex gr-total">
                        <h5>Grand Total</h5>
                        <div class="ml-auto h5"> $ 388 </div>
                    </div>
                    <hr>
                </div>
            </div>
            <div class="col-12 d-flex shopping-box"><a href="checkout.html" class="ml-auto btn hvr-hover">Checkout</a> </div>
        </div>

    </div>
</div>
<!-- End Cart -->

EADDreamCarProject/Views/Home/DisplayCarModel.cshtml
@model EADDreamCarProject.Models.DisplayCar
@{
    Layout = "~/Views/Shared/_LayoutCustomer.cshtml";
}
<!--hum ne jo controller se return karwaya model wo yaha aye ga or bcz dc ek simple model hai
    list nahi so "model" nahi likhe ge or IENumerable b nai bcz wo tab likhte jab hum ne koi
    loop laga k return karwana ho-->
<!-- Start All Title Box -->
<div class="all-title-box">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h2>Get Your Dream Car</h2>
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a href="@Url.Action("IndexCustomer","Home")">Home</a></li>
                    <li class="breadcrumb-item active">Cars</li>
                </ul>
            </div>
        </div>
    </div>
</div>
<!-- End All Title Box -->
<!-- Start Shop Page  -->
<div class="shop-box-inner">
    <div class="container">
        <div class="row">
            <div class="col-xl-3 col-lg-3 col-sm-12 col-xs-12 sidebar-shop-left">
                <div class="product-categori">
                    
                    <div class="filter-sidebar-left">
                        <div class="title-left">
                            <h3>Companies</h3>
                        </div>
                        <div class="list-group list-group-collapse list-group-sm list-group-tree" id="list-group-men" data-children=".sub-men">
                            @foreach (var c in Model.Comp)
                            {
                                <a href="@Url.Action("DisplayCarModel","Home", new {id=c.CompanyID})" class="list-group-item list-group-item-action">@c.CompanyName <small class="text-muted">(@c.CarModels.Count)</small></a>
                            }

                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xl-9 col-lg-9 col-sm-12 col-xs-12 shop-content-right">
                <div class="right-product-box">

                    <div class="row product-categorie-box">
                        <div class="tab-content">
                            <div role="tabpanel" class="tab-pane fade show active" id="grid-view">
                                <div class="row">
                                    @foreach (var cm in Model.CarMod)
                                    {
                                        <div class="col-sm-6 col-md-6 col-lg-4 col-xl-4">
                                            <div class="products-single fix">
                                                <div class="box-img-hover">
                                                    <div class="type-lb">
                                                        <p class="sale">Sale</p>
                                                    </div>
                                                    <img src="@Url.Content(cm.CarModelPicture)" style="height:40vh; width:100%" alt="Image">
                                                    <div class="mask-icon">
                                                        <a class="cart" href="@Url.Action("Create", "BuyCars")">By Now</a> <!--, new {id=cm.CarModelID}-->
                                                    </div>
                                                </div>
                                                <div class="why-text" style="height: 35vh;">
                                                    <h2 style="text-align:center; font-weight:bolder">@cm.CarModelName</h2>
                                                    <h4 style="text-align:center;">Brand: @cm.Company.CompanyName</h4>
                                                    <h4 style="text-align:center;">Description: @cm.CarModelDescription</h4>
                                                    <h4 style="text-align:center;">Fuel Type: @cm.CarModelFuelType</h4>
                                                    <h4 style="text-align:center;">Engine Capacity: @cm.CarModelEngineCapacity</h4>
                                                    <h5 style="text-align:center">Price: Rs. @cm.CarModelPrice</h5>
                                                </div>
                                            </div>
                                        </div>
                                    }

                                </div>
                            </div>
                            <div role="tabpanel" class="tab-pane fade" id="list-view">
                                <div class="list-view-box">
                                    <div class="row">
                                        <div class="col-sm-6 col-md-6 col-lg-4 col-xl-4">
                                            <div class="products-single fix">
                                                <div class="box-img-hover">
                                                    <div class="type-lb">
                                                        <p class="new">New</p>
                                                    </div>
                                                    <img src="images/img-pro-01.jpg" class="img-fluid" alt="Image">
                                                    <div class="mask-icon">
                                                        <ul>
                                                            <li><a href="#" data-toggle="tooltip" data-placement="right" title="View"><i class="fas fa-eye"></i></a></li>
                                                            <li><a href="#" data-toggle="tooltip" data-placement="right" title="Compare"><i class="fas fa-sync-alt"></i></a></li>
                                                            <li><a href="#" data-toggle="tooltip" data-placement="right" title="Add to Wishlist"><i class="far fa-heart"></i></a></li>
                                                        </ul>

                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-sm-6 col-md-6 col-lg-8 col-xl-8">
                                            <div class="why-text full-width">
                                                <h4>Lorem ipsum dolor sit amet</h4>
                                                <h5> <del>$ 60.00</del> $40.79</h5>
                                                <p>
                                                    Integer tincidunt aliquet nibh vitae dictum. In turpis sapien, imperdiet quis magna nec, iaculis ultrices ante. Integer vitae suscipit nisi. Morbi dignissim risus sit amet orci porta, eget aliquam purus
                                                    sollicitudin. Cras eu metus felis. Sed arcu arcu, sagittis in blandit eu, imperdiet sit amet eros. Donec accumsan nisi purus, quis euismod ex volutpat in. Vestibulum eleifend eros ac lobortis aliquet.
                                                    Suspendisse at ipsum vel lacus vehicula blandit et sollicitudin quam. Praesent vulputate semper libero pulvinar consequat. Etiam ut placerat lectus.
                                                </p>
                                                <a class="btn hvr-hover" href="#">Add to Cart</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="list-view-box">
                                    <div class="row">
                                        <div class="col-sm-6 col-md-6 col-lg-4 col-xl-4">
                                            <div class="products-single fix">
                                                <div class="box-img-hover">
                                                    <div class="type-lb">
                                                        <p class="sale">Sale</p>
                                                    </div>
                                                    <img src="images/img-pro-02.jpg" class="img-fluid" alt="Image">
                                                    <div class="mask-icon">
                                                        <ul>
                                                            <li><a href="#" data-toggle="tooltip" data-placement="right" title="View"><i class="fas fa-eye"></i></a></li>
                                                            <li><a href="#" data-toggle="tooltip" data-placement="right" title="Compare"><i class="fas fa-sync-alt"></i></a></li>
                                                            <li><a href="#" data-toggle="tooltip" data-placement="right" title="Add to Wishlist"><i class="far fa-heart"></i></a></li>
                                                        </ul>

                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-sm-6 col-md-6 col-lg-8 col-xl-8">
                                            <div class="why-text full-width">
                                                <h4>Lorem ipsum dolor sit amet</h4>
                                                <h5> <del>$ 60.00</del> $40.79</h5>
                                                <p>
                                                    Integer tincidunt aliquet nibh vitae dictum. In turpis sapien, imperdiet quis magna nec, iaculis ultrices ante. Integer vitae suscipit nisi. Morbi dignissim risus sit amet orci porta, eget aliquam purus
                                                    sollicitudin. Cras eu metus felis. Sed arcu arcu, sagittis in blandit eu, imperdiet sit amet eros. Donec accumsan nisi purus, quis euismod ex volutpat in. Vestibulum eleifend eros ac lobortis aliquet.
                                                    Suspendisse at ipsum vel lacus vehicula blandit et sollicitudin quam. Praesent vulputate semper libero pulvinar consequat. Etiam ut placerat lectus.
                                                </p>
                                                <a class="btn hvr-hover" href="#">Add to Cart</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="list-view-box">
                                    <div class="row">
                                        <div class="col-sm-6 col-md-6 col-lg-4 col-xl-4">
                                            <div class="products-single fix">
                                                <div class="box-img-hover">
                                                    <div class="type-lb">
                                                        <p class="sale">Sale</p>
                                                    </div>
                                                    <img src="images/img-pro-03.jpg" class="img-fluid" alt="Image">
                                                    <div class="mask-icon">
                                                        <ul>
                                                            <li><a href="#" data-toggle="tooltip" data-placement="right" title="View"><i class="fas fa-eye"></i></a></li>
                                                            <li><a href="#" data-toggle="tooltip" data-placement="right" title="Compare"><i class="fas fa-sync-alt"></i></a></li>
                                                            <li><a href="#" data-toggle="tooltip" data-placement="right" title="Add to Wishlist"><i class="far fa-heart"></i></a></li>
                                                        </ul>

                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-sm-6 col-md-6 col-lg-8 col-xl-8">
                                            <div class="why-text full-width">
                                                <h4>Lorem ipsum dolor sit amet</h4>
                                                <h5> <del>$ 60.00</del> $40.79</h5>
                                                <p>
                                                    Integer tincidunt aliquet nibh vitae dictum. In turpis sapien, imperdiet quis magna nec, iaculis ultrices ante. Integer vitae suscipit nisi. Morbi dignissim risus sit amet orci porta, eget aliquam purus
                                                    sollicitudin. Cras eu metus felis. Sed arcu arcu, sagittis in blandit eu, imperdiet sit amet eros. Donec accumsan nisi purus, quis euismod ex volutpat in. Vestibulum eleifend eros ac lobortis aliquet.
                                                    Suspendisse at ipsum vel lacus vehicula blandit et sollicitudin quam. Praesent vulputate semper libero pulvinar consequat. Etiam ut placerat lectus.
                                                </p>
                                                <a class="btn hvr-hover" href="#">Add to Cart</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Shop Page -->