EADDreamCarProject/Controllers/AdminsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EADDreamCarProject.Models;

namespace EADDreamCarProject.Controllers
{
    public class AdminsController : Controller
    {
        private Model1 db = new Model1();

        // GET: Admins
        public ActionResult Index()
        {
            return View(db.Admins.ToList());
        }

        // GET: Admins/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Admin admin = db.Admins.Find(id);
            if (admin == null)
            {
                return HttpNotFound();
            }
            return View(admin);
        }

        // GET: Admins/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admins/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Admin admin)
        {
            if (ModelState.IsValid)
            {
                //sab se pehle hum jo col ham ne upload img k liye liya us mai jo img hai usse given path 
                //peh ja k save karwaye ge or Server.MapPath is liye use kiya bcz SaveAs tiled sign ko nai 
                //pehchanta so hame pora path dena pare ga
                admin.AdminPic.SaveAs(Server.MapPath("~/dbPictures/" + admin.AdminPic.FileName));
                //pher hum nichle mai jo db mai dbPictures hai us mai AdminPic k path ko save karwaye
                //ge
                //is k ilawa hame ek folder b banana pare gaa
                //FileName likhna lazmi hai nahi to file ka name nahi target ho ga
                admin.AdminPicture = "~/dbPictures/" + admin.AdminPic.FileName;
                db.Admins.Add(admin);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(admin);
        }

        // GET: Admins/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Admin admin = db.Admins.Find(id);
            if (admin == null)
            {
                return HttpNotFound();
            }
            return View(admin);
        }

        // POST: Admins/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Admin admin)
        {
            if (ModelState.IsValid)
            {
                if (admin.AdminPic != null)
                {
                    admin.AdminPic.SaveAs(Server.MapPath("~/dbPictures/" + admin.AdminPic.FileName));
                    admin.AdminPicture = "~/dbPictures/" + admin.AdminPic.FileName;
                }
                db.Entry(admin).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(admin);
        }

        // GET: Admins/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Admin admin = db.Admins.Find(id);
            if (admin == null)
            {
                return HttpNotFound();
            }
            return View(admin);
        }

        // POST: Admins/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Admin admin = db.Admins.Find(id);
            db.Admins.Remove(admin);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EADDreamCarProject/Controllers/CarModelsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EADDreamCarProject.Models;

namespace EADDreamCarProject.Controllers
{
    public class CarModelsController : Controller
    {
        private Model1 db = new Model1();

        // GET: CarModels
        public ActionResult Index()
        {
            var carModels = db.CarModels.Include(c => c.Company);
            return View(carModels.ToList());
        }

        // GET: CarModels/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CarModel carModel = db.CarModels.Find(id);
            if (carModel == null)
            {
                return HttpNotFound();
            }
            return View(carModel);
        }

        // GET: CarModels/Create
        public ActionResult Create()
        {
            ViewBag.CompanyFID = new SelectList(db.Companies, "CompanyID", "CompanyName");
            return View();
        }

        // POST: CarModels/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CarModel carModel)
        {
            if (ModelState.IsValid)
            {
                //sab se pehle hum jo col ham ne upload img k liye liya us mai jo img hai usse given path 
                //peh ja k save karwaye ge or Server.MapPath is liye use kiya bcz SaveAs tiled sign ko nai 
                //pehchanta so hame pora path dena pare ga
                carModel.CarModelPic.SaveAs(Server.MapPath("~/dbPictures/" + carModel.CarModelPic.FileName));
                //pher hum nichle mai jo db mai CarModelPicture hai us mai CarModelPic k path ko save karwaye
                //ge
                //is k ilawa hame ek folder b banana pare gaa
                //FileName likhna lazmi hai nahi to file ka name nahi target ho ga
                carModel.CarModelPicture = "~/dbPictures/" + carModel.CarModelPic.FileName;
                db.CarModels.Add(carModel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CompanyFID = new SelectList(db.Companies, "CompanyID", "CompanyName", carModel.CompanyFID);
            return View(carModel);
        }

        // GET: CarModels/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CarModel carModel = db.CarModels.Find(id);
            if (carModel == null)
            {
                return HttpNotFound();
            }
            ViewBag.CompanyFID = new SelectList(db.Companies, "CompanyID", "CompanyName", carModel.CompanyFID);
            return View(carModel);
        }

        // POST: CarModels/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CarModel carModel)
        {
            if (ModelState.IsValid)
            {
                if (carModel.CarModelPic != null)
                {
                    carModel.CarModelPic.SaveAs(Server.MapPath("~/dbPictures/" + carModel.CarModelPic.FileName));
                    carModel.CarModelPicture = "~/dbPictures/" + carModel.CarModelPic.FileName;
                }
                db.Entry(carModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CompanyFID = new SelectList(db.Companies, "CompanyID", "CompanyName", carModel.CompanyFID);
            return View(carModel);
        }

        // GET: CarModels/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CarModel carModel = db.CarModels.Find(id);
            if (carModel == null)
            {
                return HttpNotFound();
            }
            return View(carModel);
        }

        // POST: CarModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CarModel carModel = db.CarModels.Find(id);
            db.CarModels.Remove(carModel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EADDreamCarProject/Controllers/CompaniesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EADDreamCarProject.Models;

namespace EADDreamCarProject.Controllers
{
    public class CompaniesController : Controller
    {
        private Model1 db = new Model1();

        // GET: Companies
        public ActionResult Index()
        {
            return View(db.Companies.ToList());
        }

        // GET: Companies/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Company company = db.Companies.Find(id);
            if (company == null)
            {
                return HttpNotFound();
            }
            return View(company);
        }

        // GET: Companies/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Companies/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CompanyID,CompanyName,CompanyRegistrationNo,CompanyEmail,CompanyContact")] Company company)
        {
            if (ModelState.IsValid)
            {
                db.Companies.Add(company);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(company);
        }

        // GET: Companies/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Company company = db.Companies.Find(id);
            if (company == null)
            {
                return HttpNotFound();
            }
            return View(company);
        }

        // POST: Companies/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CompanyID,CompanyName,CompanyRegistrationNo,CompanyEmail,CompanyContact")] Company company)
        {
            if (ModelState.IsValid)
            {
                db.Entry(company).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(company);
        }

        // GET: Companies/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Company company = db.Companies.Find(id);
            if (company == null)
            {
                return HttpNotFound();
            }
            return View(company);
        }

        // POST: Companies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Company company = db.Companies.Find(id);
            db.Companies.Remove(company);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EADDreamCarProject/Controllers/ShowroomsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EADDreamCarProject.Models;

namespace EADDreamCarProject.Controllers
{
    public class ShowroomsController : Controller
    {
        private Model1 db = new Model1();

        // GET: Showrooms
        public ActionResult Index()
        {
            return View(db.Showrooms.ToList());
        }

        // GET: Showrooms/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Showroom showroom = db.Showrooms.Find(id);
            if (showroom == null)
            {
                return HttpNotFound();
            }
            return View(showroom);
        }

        // GET: Showrooms/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Showrooms/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ShowroomID,ShowroomName,ShowroomCity,ShowroomAddress,ShowroomContact,ShowroomEmail")] Showroom showroom)
        {
            if (ModelState.IsValid)
            {
                db.Showrooms.Add(showroom);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(showroom);
        }

        // GET: Showrooms/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Showroom showroom = db.Showrooms.Find(id);
            if (showroom == null)
            {
                return HttpNotFound();
            }
            return View(showroom);
        }

        // POST: Showrooms/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ShowroomID,ShowroomName,ShowroomCity,ShowroomAddress,ShowroomContact,ShowroomEmail")] Showroom showroom)
        {
            if (ModelState.IsValid)
            {
                db.Entry(showroom).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(showroom);
        }

        // GET: Showrooms/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Showroom showroom = db.Showrooms.Find(id);
            if (showroom == null)
            {
                return HttpNotFound();
            }
            return View(showroom);
        }

        // POST: Showrooms/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Showroom showroom = db.Showrooms.Find(id);
            db.Showrooms.Remove(showroom);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EADDreamCarProject/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>DreamCar - Admin Template</title>
    <!-- BOOTSTRAP STYLES-->
    <link href="~/Content/AdminTemplate/assets/css/bootstrap.css" rel="stylesheet" />
    <!-- FONTAWESOME STYLES-->
    <link href="~/Content/AdminTemplate/assets/css/font-awesome.css" rel="stylesheet" />
    <!-- MORRIS CHART STYLES-->
    <link href="~/Content/AdminTemplate/assets/js/morris/morris-0.4.3.min.css" rel="stylesheet" />
    <!-- CUSTOM STYLES-->
    <link href="~/Content/AdminTemplate/assets/css/custom.css" rel="stylesheet" />
    <!-- GOOGLE FONTS-->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />
</head>
<body>
    <div id="wrapper">
        <nav class="navbar navbar-default navbar-cls-top " role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand"  href="">Admin Panel</a>
            </div>
            <div style="color: white;
                padding: 15px 50px 5px 50px;
                float: right;
                font-size: 16px;">&nbsp; <a href="@Url.Action("IndexCustomer","Home")" class="btn btn-danger square-btn-adjust">Logout</a> </div>
        </nav>
        <!-- /. NAV TOP  -->

        <nav class="navbar-default navbar-side" style="background-color:maroon;" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav" id="main-menu">
                   


                    <li>
                        <a href="@Url.Action("IndexAdmin","Home")"><i class="fa fa-calendar fa-3x"></i> Dashboard</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index","Admins")"><i class="fa fa-user fa-3x"></i> Manage Admin Accounts</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index","Companies")"><i class="fa fa-building-o fa-3x"></i> Manage Companies</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index","CarModels")"><i class="fa fa-truck fa-3x"></i> Manage Car Models</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index","Showrooms")"><i class="fa fa-home fa-3x"></i> Manage Showrooms</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index","Customers")"><i class="fa fa-user fa-3x"></i> Manage Customers</a>
                    </li>

                </ul>

            </div>

        </nav>
        <!-- /. NAV SIDE  -->

        <div id="page-wrapper">
            <div id="page-inner">
                <div class="row">
                    <div class="col-md-12">
                        <center><h2>Admin Dashboard</h2></center>

                    </div>
                </div>
                <!-- /. ROW  -->
                <hr />



                @RenderBody()


            </div>
            <!-- /. PAGE INNER  -->
        </div>
        <!-- /. PAGE WRAPPER  -->
    </div>
    <!-- /. WRAPPER  -->
    <!-- SCRIPTS -AT THE BOTOM TO REDUCE THE LOAD TIME-->
    <!-- JQUERY SCRIPTS -->
    <script src="~/Content/AdminTemplate/assets/js/jquery-1.10.2.js"></script>
    <!-- BOOTSTRAP SCRIPTS -->
    <script src="~/Content/AdminTemplate/assets/js/bootstrap.min.js"></script>
    <!-- METISMENU SCRIPTS -->
    <script src="~/Content/AdminTemplate/assets/js/jquery.metisMenu.js"></script>
    <!-- MORRIS CHART SCRIPTS -->
    <script src="~/Content/AdminTemplate/assets/js/morris/raphael-2.1.0.min.js"></script>
    <script src="~/Content/AdminTemplate/assets/js/morris/morris.js"></script>
    <!-- CUSTOM SCRIPTS -->
    <script src="~/Content/AdminTemplate/assets/js/custom.js"></script>


</body>
</html>

EADDreamCarProject/Views/Shared/_LayoutCustomer.cshtml
<!DOCTYPE html>
<html lang="en">
<!-- Basic -->

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Site Metas -->
    <title>DreamCar - Customer Template</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Site Icons -->
    <link rel="shortcut icon" href="~/Content/CustomerTemplate/images/favicon.ico" type="image/x-icon">
    <link rel="apple-touch-icon" href="~/Content/CustomerTemplate/images/apple-touch-icon.png">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="~/Content/CustomerTemplate/css/bootstrap.min.css">
    <!-- Site CSS -->
    <link rel="stylesheet" href="~/Content/CustomerTemplate/css/style.css">
    <!-- Responsive CSS -->
    <link rel="stylesheet" href="~/Content/CustomerTemplate/css/responsive.css">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="~/Content/CustomerTemplate/css/custom.css">

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>


    <!-- Start Main Top -->
    <header class="main-header">
        <!-- Start Navigation -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light navbar-default bootsnav">
            <div class="container">
                <!-- Start Header Navigation -->
                <div class="navbar-header">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-menu" aria-controls="navbars-rs-food" aria-expanded="false" aria-label="Toggle navigation">
                        <i class="fa fa-bars"></i>
                    </button>
                    <a class="navbar-brand" style="font-size:3em; color:red; font-weight:bolder;" href="index.html">DreamCar</a>
                </div>
                <!-- End Header Navigation -->
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="navbar-menu">
                    <ul class="nav navbar-nav ml-auto" data-in="fadeInDown" data-out="fadeOutUp">
                        <li class="nav-item active"><a class="nav-link" href="@Url.Action("IndexCustomer","Home")"><i class="fa fa-home"></i> Home</a></li>
                        <li class="nav-item active"><a class="nav-link" href="@Url.Action("About","Home")"><i class="fa fa-address-book"></i> About Us</a></li>
                        <li class="nav-item active"><a class="nav-link" href="@Url.Action("DisplayCarModel","Home")"><i class="fa fa-car"></i> Cars</a></li>
                        <li class="nav-item active"><a class="nav-link" href="@Url.Action("DisplayShowroom","Home")"><i class="fa fa-building"></i> Showrooms</a></li>
                        <li class="nav-item active"><a class="nav-link" href="@Url.Action("Client","Home")"><i class="fa fa-user-astronaut"></i> Clients</a></li>
                        <li class="nav-item active"><a class="nav-link" href="@Url.Action("Login","Home")"><i class="fa fa-user-alt"></i> Admin Login</a></li>
                    </ul>
                </div>
                <!-- /.navbar-collapse -->
            
            </div>
            <!-- Start Side Menu -->
            <div class="side">
                <a href="#" class="close-side"><i class="fa fa-times"></i></a>
                <li class="cart-box">
                    <ul class="cart-list">
                        <li>
                            <a href="#" class="photo"><img src="~/Content/CustomerTemplate/images/img-pro-01.jpg" class="cart-thumb" alt="" /></a>
                            <h6><a href="#">Delica omtantur </a></h6>
                            <p>1x - <span class="price">$80.00</span></p>
                        </li>
                        <li>
                            <a href="#" class="photo"><img src="~/Content/CustomerTemplate/images/img-pro-02.jpg" class="cart-thumb" alt="" /></a>
                            <h6><a href="#">Omnes ocurreret</a></h6>
                            <p>1x - <span class="price">$60.00</span></p>
                        </li>
                        <li>
                            <a href="#" class="photo"><img src="~/Content/CustomerTemplate/images/img-pro-03.jpg" class="cart-thumb" alt="" /></a>
                            <h6><a href="#">Agam facilisis</a></h6>
                            <p>1x - <span class="price">$40.00</span></p>
                        </li>
                        <li class="total">
                            <a href="#" class="btn btn-default hvr-hover btn-cart">VIEW CART</a>
                            <span class="float-right"><strong>Total</strong>: $180.00</span>
                        </li>
                    </ul>
                </li>
            </div>
            <!-- End Side Menu -->
        </nav>
        <!-- End Navigation -->
    </header>
    <!-- End Main Top -->
    <!-- Start Top Search -->
    <div class="top-search">
        <div class="container">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-search"></i></span>
                <input type="text" class="form-control" placeholder="Search">
                <span class="input-group-addon close-search"><i class="fa fa-times"></i></span>
            </div>
        </div>
    </div>
    <!-- End Top Search -->



    @RenderBody()




    <!-- Start copyright  -->
    <div class="footer-copyright">
        <p class="footer-company">
            All Rights Reserved. &copy; 2022 <a href="#">Honey Productions,</a> Design By : Osama Maarouf
        </p>
    </div>
    <!-- End copyright  -->

    <a href="#" id="back-to-top" title="Back to top" style="display: none;">&uarr;</a>

    <!-- ALL JS FILES -->
    <script src="~/Content/CustomerTemplate/js/jquery-3.2.1.min.js"></script>
    <script src="~/Content/CustomerTemplate/js/popper.min.js"></script>
    <script src="~/Content/CustomerTemplate/js/bootstrap.min.js"></script>
    <!-- ALL PLUGINS -->
    <script src="~/Content/CustomerTemplate/js/jquery.superslides.min.js"></script>
    <script src="~/Content/CustomerTemplate/js/bootstrap-select.js"></script>
    <script src="~/Content/CustomerTemplate/js/inewsticker.js"></script>
    <script src="~/Content/CustomerTemplate/js/bootsnav.js."></script>
    <script src="~/Content/CustomerTemplate/js/images-loded.min.js"></script>
    <script src="~/Content/CustomerTemplate/js/isotope.min.js"></script>
    <script src="~/Content/CustomerTemplate/js/owl.carousel.min.js"></script>
    <script src="~/Content/CustomerTemplate/js/baguetteBox.min.js"></script>
    <script src="~/Content/CustomerTemplate/js/form-validator.min.js"></script>
    <script src="~/Content/CustomerTemplate/js/contact-form-script.js"></script>
    <script src="~/Content/CustomerTemplate/js/custom.js"></script>
</body>

</html>